"""Product catalog seed data, mirrored from the React frontend (src/data/products.js)."""

PRODUCTS: list[dict] = [
    {"id": 'prod-d1', "name": 'Barette (Net)', "category": 'headwear', "price": 150, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Standard barette with net.'},
    {"id": 'prod-d2', "name": 'Barette (Without Net)', "category": 'headwear', "price": 120, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Standard barette without net.'},
    {"id": 'prod-d3', "name": 'Barette Badge', "category": 'accessories', "price": 50, "badge": 'army', "image": '/assets/rank_stars.png', "description": 'Badge for barette.'},
    {"id": 'prod-d4', "name": 'Pom Pom', "category": 'accessories', "price": 30, "badge": 'army', "image": '/assets/red_hackle.png', "description": 'Pom pom for headwear.'},
    {"id": 'prod-d5', "name": 'Heckel', "category": 'accessories', "price": 80, "badge": 'army', "image": '/assets/red_hackle.png', "description": 'Heckel for beret.'},
    {"id": 'prod-d6', "name": 'Line Yard', "category": 'accessories', "price": 100, "badge": 'army', "image": '/assets/lanyard.png', "description": 'Standard line yard.'},
    {"id": 'prod-d7', "name": 'C-Line Yard (Motu)', "category": 'accessories', "price": 120, "badge": 'army', "image": '/assets/lanyard.png', "description": 'Thick C-Line yard.'},
    {"id": 'prod-d8', "name": 'Arm Badge', "category": 'accessories', "price": 60, "badge": 'army', "image": '/assets/rank_stars.png', "description": 'Cloth arm badge.'},
    {"id": 'prod-d9', "name": 'Arm Badge (Plastic)', "category": 'accessories', "price": 80, "badge": 'army', "image": '/assets/rank_stars.png', "description": 'Plastic arm badge.'},
    {"id": 'prod-d10', "name": 'B-Belt (Black)', "category": 'accessories', "price": 200, "badge": 'army', "image": '/assets/leather_belt.png', "description": 'Black B-Belt.'},
    {"id": 'prod-d11', "name": 'C-Belt (Leather)', "category": 'accessories', "price": 450, "badge": 'army', "image": '/assets/leather_belt.png', "description": 'Leather C-Belt.'},
    {"id": 'prod-d12', "name": 'Socks', "category": 'clothing', "price": 100, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Uniform socks.'},
    {"id": 'prod-d13', "name": 'Scarf', "category": 'clothing', "price": 150, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Uniform scarf.'},
    {"id": 'prod-d14', "name": 'Kamar Band & Jalar', "category": 'clothing', "price": 350, "badge": 'army', "image": '/assets/leather_belt.png', "description": 'Ceremonial kamar band.'},
    {"id": 'prod-d15', "name": 'Hand Gloves', "category": 'accessories', "price": 150, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'White parade gloves.'},
    {"id": 'prod-d16', "name": 'Anklet-Rexin', "category": 'accessories', "price": 200, "badge": 'army', "image": '/assets/dms_boots.png', "description": 'Rexin anklets for boots.'},
    {"id": 'prod-d17', "name": 'Anklets-Cloth', "category": 'accessories', "price": 150, "badge": 'army', "image": '/assets/dms_boots.png', "description": 'Cloth anklets.'},
    {"id": 'prod-d18', "name": 'Red Patti', "category": 'accessories', "price": 80, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Red patti.'},
    {"id": 'prod-d19', "name": 'NCC XCap (Blue)', "category": 'headwear', "price": 200, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Blue NCC XCap.'},
    {"id": 'prod-d20', "name": 'Army Cap (Jungle)', "category": 'headwear', "price": 250, "badge": 'army', "image": '/assets/military_uniform.png', "description": 'Jungle camouflage cap.'},
    {"id": 'prod-d21', "name": 'Cane (Black/Brown)', "category": 'accessories', "price": 400, "badge": 'army', "image": '/assets/lanyard.png', "description": 'Officer cane stick.'},
    {"id": 'prod-d22', "name": 'CPL Badge', "category": 'accessories', "price": 50, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'Corporal rank badge.'},
    {"id": 'prod-d23', "name": 'LCPL Badge', "category": 'accessories', "price": 50, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'Lance Corporal badge.'},
    {"id": 'prod-d24', "name": 'SUO Badge', "category": 'accessories', "price": 100, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'SUO rank badge.'},
    {"id": 'prod-d25', "name": 'JUO Badge', "category": 'accessories', "price": 100, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'JUO rank badge.'},
    {"id": 'prod-d26', "name": 'CQMS (Watch)', "category": 'accessories', "price": 250, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'CQMS badge/watch.'},
    {"id": 'prod-d27', "name": 'NCC ID Cards', "category": 'accessories', "price": 50, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Blank NCC ID cards.'},
    {"id": 'prod-d28', "name": 'Map', "category": 'tactical', "price": 100, "badge": 'general', "image": '/assets/backpack.png', "description": 'Training map.'},
    {"id": 'prod-d29', "name": 'Sargent Badge', "category": 'accessories', "price": 80, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'Sargent rank badge.'},
    {"id": 'prod-d30', "name": 'b-line yard (medium)', "category": 'accessories', "price": 90, "badge": 'army', "image": '/assets/lanyard.png', "description": 'Medium line yard.'},
    {"id": 'prod-d31', "name": 'a-line yard (small)', "category": 'accessories', "price": 80, "badge": 'army', "image": '/assets/lanyard.png', "description": 'Small line yard.'},
    {"id": 'prod-n1', "name": 'P-Cap', "category": 'headwear', "price": 300, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'NCC P-Cap.'},
    {"id": 'prod-n2', "name": 'P-Cap Badge', "category": 'accessories', "price": 60, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'Badge for P-Cap.'},
    {"id": 'prod-n3', "name": 'ANO-2 Star', "category": 'accessories', "price": 150, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'ANO 2-Star rank.'},
    {"id": 'prod-n4', "name": 'ANO-3 Star', "category": 'accessories', "price": 200, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'ANO 3-Star rank.'},
    {"id": 'prod-n5', "name": 'Table Cloth', "category": 'general', "price": 400, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Official table cloth.'},
    {"id": 'prod-n6', "name": 'Table Flag', "category": 'general', "price": 150, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Small table flag.'},
    {"id": 'prod-n7', "name": 'NCC & National Flag (Table)', "category": 'general', "price": 250, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Combo table flags.'},
    {"id": 'prod-n8', "name": 'NCC Flag', "category": 'general', "price": 500, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'Large NCC flag.'},
    {"id": 'prod-n9', "name": 'T-Flag', "category": 'general', "price": 300, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'T-Flag.'},
    {"id": 'prod-n10', "name": 'ANO-Scarf', "category": 'clothing', "price": 200, "badge": 'ncc', "image": '/assets/ncc_uniform.png', "description": 'ANO special scarf.'},
    {"id": 'prod-n11', "name": 'ANO-Badge', "category": 'accessories', "price": 100, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'ANO Badge.'},
    {"id": 'prod-n12', "name": 'ANO-SD, SW & JD 9Star Neeche', "category": 'accessories', "price": 300, "badge": 'ncc', "image": '/assets/rank_stars.png', "description": 'Special 9-star badge set.'},
    {"id": 'prod-af1', "name": 'Air Force Cap', "category": 'headwear', "price": 350, "badge": 'airforce', "image": '/assets/airforce_uniform.png', "description": 'Air Force cap.'},
    {"id": 'prod-af2', "name": 'Air Force Arm Badge', "category": 'accessories', "price": 80, "badge": 'airforce', "image": '/assets/rank_stars.png', "description": 'Air Force arm badge.'},
    {"id": 'prod-af3', "name": 'Air Force Belt', "category": 'accessories', "price": 250, "badge": 'airforce', "image": '/assets/leather_belt.png', "description": 'Air Force web belt.'},
    {"id": 'prod-af4', "name": 'Air Force Line Yard', "category": 'accessories', "price": 120, "badge": 'airforce', "image": '/assets/lanyard.png', "description": 'Air Force line yard.'},
    {"id": 'prod-af5', "name": 'Air Force Socks', "category": 'clothing', "price": 100, "badge": 'airforce', "image": '/assets/airforce_uniform.png', "description": 'Air Force uniform socks.'},
    {"id": 'prod-nv1', "name": 'NCC Navy Belt', "category": 'accessories', "price": 250, "badge": 'navy', "image": '/assets/leather_belt.png', "description": 'Navy web belt.'},
    {"id": 'prod-nv2', "name": 'Navy Arm Badges', "category": 'accessories', "price": 80, "badge": 'navy', "image": '/assets/rank_stars.png', "description": 'Navy arm badges.'},
    {"id": 'prod-nv3', "name": 'Navy White Socks', "category": 'clothing', "price": 100, "badge": 'navy', "image": '/assets/navy_uniform.png', "description": 'Navy white socks.'},
    {"id": 'prod-nv4', "name": 'Navy Cap', "category": 'headwear', "price": 350, "badge": 'navy', "image": '/assets/navy_uniform.png', "description": 'Navy cap.'},
    {"id": 'prod-nv5', "name": 'Navy Line Yard', "category": 'accessories', "price": 120, "badge": 'navy', "image": '/assets/lanyard.png', "description": 'Navy line yard.'},
    {"id": 'prod-sg1', "name": 'Scouts Barret', "category": 'headwear', "price": 150, "badge": 'scouts', "image": '/assets/ncc_uniform.png', "description": 'Scouts barret.'},
    {"id": 'prod-sg2', "name": 'Scouts Barret Badge', "category": 'accessories', "price": 50, "badge": 'scouts', "image": '/assets/rank_stars.png', "description": 'Scouts barret badge.'},
    {"id": 'prod-sg3', "name": 'Scouts Scarf', "category": 'clothing', "price": 100, "badge": 'scouts', "image": '/assets/ncc_uniform.png', "description": 'Scouts uniform scarf.'},
    {"id": 'prod-sg4', "name": 'Vocal Guard', "category": 'accessories', "price": 80, "badge": 'scouts', "image": '/assets/lanyard.png', "description": 'Vocal guard.'},
    {"id": 'prod-sg5', "name": 'Scouts Line Yard', "category": 'accessories', "price": 90, "badge": 'scouts', "image": '/assets/lanyard.png', "description": 'Scouts line yard.'},
    {"id": 'prod-sg6', "name": 'Badges - Scouts & Guides', "category": 'accessories', "price": 150, "badge": 'scouts', "image": '/assets/rank_stars.png', "description": 'Assorted scouts & guides badges.'},
    {"id": 'prod-sg7', "name": 'Belt (Boys)', "category": 'accessories', "price": 200, "badge": 'scouts', "image": '/assets/leather_belt.png', "description": 'Scouts boys belt.'},
    {"id": 'prod-sg8', "name": 'Belt (Girls)', "category": 'accessories', "price": 200, "badge": 'scouts', "image": '/assets/leather_belt.png', "description": 'Guides girls belt.'},
    {"id": 'prod-sf1', "name": 'Cap - Security Force', "category": 'headwear', "price": 250, "badge": 'security', "image": '/assets/military_uniform.png', "description": 'Security force cap.'},
    {"id": 'prod-sf2', "name": 'Badge - Security Force', "category": 'accessories', "price": 60, "badge": 'security', "image": '/assets/rank_stars.png', "description": 'Security force badge.'},
    {"id": 'prod-sf3', "name": 'Line Yard - Security Force', "category": 'accessories', "price": 100, "badge": 'security', "image": '/assets/lanyard.png', "description": 'Security force line yard.'},
    {"id": 'prod-sf4', "name": 'Belt - Security Force', "category": 'accessories', "price": 200, "badge": 'security', "image": '/assets/leather_belt.png', "description": 'Security force belt.'},
    {"id": 'prod-sf5', "name": 'Stick - Security Force E', "category": 'tactical', "price": 350, "badge": 'security', "image": '/assets/backpack.png', "description": 'Security guard stick/baton.'},
    {"id": 'prod-pf1', "name": 'APP Big Cap Badges', "category": 'accessories', "price": 120, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Big cap badges for police.'},
    {"id": 'prod-pf2', "name": 'APP Normal Badges', "category": 'accessories', "price": 80, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Normal police badges.'},
    {"id": 'prod-pf3', "name": 'Stars Big', "category": 'accessories', "price": 100, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Large rank stars.'},
    {"id": 'prod-pf4', "name": 'Stars Small', "category": 'accessories', "price": 80, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Small rank stars.'},
    {"id": 'prod-pf5', "name": 'Shoulder Badges (APPH, APPS)', "category": 'accessories', "price": 150, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Police shoulder badges.'},
    {"id": 'prod-pf6', "name": 'Khaki Simbles', "category": 'clothing', "price": 250, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Khaki uniform symbols.'},
    {"id": 'prod-pf7', "name": 'Glitter Khaki Simbles', "category": 'clothing', "price": 300, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Glitter khaki symbols.'},
    {"id": 'prod-pf8', "name": 'ID Cards Chains', "category": 'accessories', "price": 50, "badge": 'police', "image": '/assets/lanyard.png', "description": 'Chains for ID cards.'},
    {"id": 'prod-pf9', "name": 'Belt Leathers', "category": 'accessories', "price": 450, "badge": 'police', "image": '/assets/leather_belt.png', "description": 'Leather police belts.'},
    {"id": 'prod-pf10', "name": 'Belt Cotton', "category": 'accessories', "price": 200, "badge": 'police', "image": '/assets/leather_belt.png', "description": 'Cotton police belts.'},
    {"id": 'prod-pf11', "name": 'Buckles (APP, AISF, FIRE)', "category": 'accessories', "price": 150, "badge": 'police', "image": '/assets/leather_belt.png', "description": 'Police/Fire brass buckles.'},
    {"id": 'prod-pf12', "name": 'Khaki Training Socks', "category": 'clothing', "price": 100, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Khaki socks for training.'},
    {"id": 'prod-pf13', "name": 'Shoes Laces', "category": 'accessories', "price": 40, "badge": 'police', "image": '/assets/dms_boots.png', "description": 'Durable boot laces.'},
    {"id": 'prod-pf14', "name": 'Shoes Polishers', "category": 'accessories', "price": 80, "badge": 'police', "image": '/assets/dms_boots.png', "description": 'Shoe polish tin.'},
    {"id": 'prod-pf15', "name": 'Shoes Shiners', "category": 'accessories', "price": 60, "badge": 'police', "image": '/assets/dms_boots.png', "description": 'Instant shoe shiner.'},
    {"id": 'prod-pf16', "name": 'Polishes Brushes', "category": 'accessories', "price": 100, "badge": 'police', "image": '/assets/dms_boots.png', "description": 'Shoe polish brush.'},
    {"id": 'prod-pf17', "name": 'P-Cap (All Sizes)', "category": 'headwear', "price": 350, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Police P-Cap.'},
    {"id": 'prod-pf18', "name": 'D-Cap (All Sizes)', "category": 'headwear', "price": 350, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Police D-Cap.'},
    {"id": 'prod-pf19', "name": 'P-Cap Khaki', "category": 'headwear', "price": 350, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Khaki Police P-Cap.'},
    {"id": 'prod-pf20', "name": 'Whistle', "category": 'accessories', "price": 80, "badge": 'police', "image": '/assets/lanyard.png', "description": 'Metal whistle.'},
    {"id": 'prod-pf21', "name": 'Whistle Gurds Green Colour', "category": 'accessories', "price": 50, "badge": 'police', "image": '/assets/lanyard.png', "description": 'Green whistle guard.'},
    {"id": 'prod-pf22', "name": 'Wooden Lathi Stick (with tread)', "category": 'tactical', "price": 250, "badge": 'police', "image": '/assets/backpack.png', "description": 'Standard wooden lathi.'},
    {"id": 'prod-pf23', "name": 'Souls Pads', "category": 'accessories', "price": 100, "badge": 'police', "image": '/assets/dms_boots.png', "description": 'Shoe sole pads.'},
    {"id": 'prod-pf24', "name": 'Ground Sheets', "category": 'tactical', "price": 400, "badge": 'police', "image": '/assets/backpack.png', "description": 'Waterproof ground sheet.'},
    {"id": 'prod-pf25', "name": 'Sling', "category": 'tactical', "price": 200, "badge": 'police', "image": '/assets/backpack.png', "description": 'Rifle sling.'},
    {"id": 'prod-pf26', "name": 'Cap Badge (APP-Big Size, APP-Small)', "category": 'accessories', "price": 120, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Cap badges.'},
    {"id": 'prod-pf27', "name": 'Magazine Pouches, Chains', "category": 'tactical', "price": 350, "badge": 'police', "image": '/assets/backpack.png', "description": 'Ammunition magazine pouches.'},
    {"id": 'prod-pf28', "name": 'Rifle Chains', "category": 'tactical', "price": 150, "badge": 'police', "image": '/assets/backpack.png', "description": 'Chains for securing rifles.'},
    {"id": 'prod-pf29', "name": 'Handcuffs', "category": 'tactical', "price": 650, "badge": 'police', "image": '/assets/leather_belt.png', "description": 'Standard steel handcuffs.'},
    {"id": 'prod-pf30', "name": 'Gun Cover Leather', "category": 'tactical', "price": 550, "badge": 'police', "image": '/assets/leather_belt.png', "description": 'Leather gun holster/cover.'},
    {"id": 'prod-pf31', "name": 'Walky Talky', "category": 'tactical', "price": 2500, "badge": 'police', "image": '/assets/backpack.png', "description": 'Radio walkie talkie set.'},
    {"id": 'prod-pf32', "name": 'Shoulder Badges (Red, Green, Blue, Black)', "category": 'accessories', "price": 150, "badge": 'police', "image": '/assets/rank_stars.png', "description": 'Coloured shoulder badges.'},
    {"id": 'prod-pf33', "name": 'Traffic Constable Round White Cap', "category": 'headwear', "price": 300, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'White traffic police cap.'},
    {"id": 'prod-pf34', "name": 'D-Cap Glitter', "category": 'headwear', "price": 350, "badge": 'police', "image": '/assets/military_uniform.png', "description": 'Glitter D-Cap.'},
    {"id": 'prod-pf35', "name": 'Whistle Gurds Double Rope Black', "category": 'accessories', "price": 80, "badge": 'police', "image": '/assets/lanyard.png', "description": 'Double rope black whistle guard.'},
]
